yellow/models.py
import os, re, random
from typing import Optional, List
from datetime import datetime

from peewee import SqliteDatabase, SQL, ForeignKeyField
import peewee as pw

import settings

db = SqliteDatabase(settings.DB_PATH)


class User(pw.Model):
    id = pw.UUIDField(primary_key=True)
    created: datetime = pw.DateTimeField(default=datetime.now)
    username = pw.CharField(unique=True, null=False)
    address = pw.CharField(null=True)

    @property
    def created_dt(self):
        return self.created.strftime('%Y-%m-%d')

    @staticmethod
    async def search(needle) -> List['User']:
        if not needle:
            raise Exception("need search term")
        needle = needle.replace("*", "")
        needle = needle.lower()

        return User.select().where(
            User.address.is_null(False),
            User.username % f"*{needle}*"
        )

    def to_json(self, ignore_key=None):
        data = {
            "id": self.id,
            "username": self.username,
            "address": self.address
        }
        if isinstance(ignore_key, str):
            data.pop(ignore_key)
        return data

    class Meta:
        database = db

yellow/__init__.py
from quart import session, abort

from functools import wraps


def login_required(func):
    @wraps(func)
    async def wrapper(*args, **kwargs):
        user = session.get('user')
        if not isinstance(user, dict):
            abort(403)
        return await func(*args, **kwargs)
    return wrapper

yellow/auth.py
import re

import peewee
from quart import session, redirect, url_for, current_app
from quart_keycloak import Keycloak, KeycloakAuthToken, KeycloakLogoutRequest
from yellow.factory import keycloak
from yellow.models import User


@keycloak.after_login()
async def handle_user_login(auth_token: KeycloakAuthToken):
    username = auth_token.username
    uid = auth_token.sub

    if not re.match(r"^[a-zA-Z0-9_\.-]+$", username):
        raise Exception("bad username")

    try:
        user = User.select().where(User.username == username).get()
    except Exception as ex:
        user = None

    if not user:
        # create new user if it does not exist yet
        current_app.logger.info(f'User {username} not found, creating')
        try:
            user = User.create(id=uid, username=username)
        except Exception as ex:
            current_app.logger.debug(f'User {username}, creation error')
            raise

    # user is now logged in
    session['user'] = user.to_json()
    return redirect(url_for('bp_routes.dashboard'))

yellow/routes.py
from quart import render_template, request, redirect, url_for, jsonify, Blueprint, abort, flash, send_from_directory, session
import re

from yellow import login_required
from yellow.models import User

bp_routes = Blueprint('bp_routes', __name__)


@bp_routes.get("/")
async def root():
    return await render_template('index.html')


@bp_routes.route("/login")
async def login():
    from yellow.factory import keycloak
    return redirect(url_for(keycloak.endpoint_name_login))


@bp_routes.route("/logout")
@login_required
async def logout():
    session['user'] = None
    return redirect(url_for('bp_routes.root'))


@bp_routes.route("/dashboard")
@login_required
async def dashboard():
    return await render_template('dashboard.html')


@bp_routes.post("/dashboard/address")
@login_required
async def dashboard_address_post():
    form = await request.form
    address = form.get('address')
    if len(address) not in [97, 108]:
        raise Exception("Please submit a WOW address")

    # update user
    from yellow.models import User
    user = User.select().filter(User.id == session['user']['id']).get()
    user.address = address
    user.save()
    session['user'] = user.to_json()

    return await render_template('dashboard.html')


@bp_routes.post("/dashboard/address/delete")
@login_required
async def dashboard_address_delete():
    from yellow.models import User
    user = User.select().filter(User.id == session['user']['id']).get()
    user.address = None
    user.save()
    session['user'] = user.to_json()
    return redirect(url_for("bp_routes.dashboard"))


@bp_routes.route("/search")
async def search():
    needle = request.args.get('username')
    if needle:
        users = [u for u in await User.search(needle)]
        if users:
            return await render_template('search_results.html', users=users)
        else:
            return await render_template('search_results.html')

    q = User.select()
    q = q.where(User.address.is_null(False))
    q = q.limit(100)

    users = [u for u in q]
    return await render_template('search.html', users=users)


@bp_routes.route("/user/<path:name>")
async def user_page(name: str):
    if not name:
        raise Exception("invalid name")
    name = name.lower()

    try:
        _user = User.select().where(
            User.username == name,
            User.address.is_null(False)
        ).get()
    except:
        return abort(404)

    return await render_template('user.html', users=[_user])


@bp_routes.route("/about")
async def about():
    return await render_template('about.html')

yellow/templates/about.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - About{% endblock %}
</div>

<div id="main">
    <h1>About</h1>
    <p>
        Search for any Wownero <em>address</em> you want by username and pay
        the world!
        <br>
        This application uses <u>Wownero's Centralized Authentication Service.</u>
    </p>
    <p>
        Other Wownero related stuff:
        <br>
        <a href="https://wownero.org/">WebSite</a>
        <br>
        <a href="https://suchwow.xyz">SuchWow</a>
        <br>
        <a href="https://git.wownero.com">Official Git</a>
        <br>
        <a href="https://discord.com/invite/ykZyAzJhDK">Discord server</a>
    </p>
    <p>
        Made by <a href="https://notmtth.xyz">NotMtth</a> and <code>dsc</code>
    </p>
</div>

<style>
    #main{
        width: 100%;
        height: 80vh;
        display: grid;
        place-content: center;
        text-align: center;
    }
    form{
        height: 50px;
    }
    @media (max-width: 800px) {
        kbd{
            width: 100vw;
        }
    }
</style>

{% endblock %}

yellow/templates/api.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - API{% endblock %}
</div>

<div id="main">
  <h1>API</h1>
  <p>
    Search user: <code><a href="/api/user/dsc" data-tooltip="partial search supported">/api/user/{username}</a></code>
    <br><br>
    Get all users: <code><a href="/api/user/">/api/user/</a></code>
  </p>
</div>

<style>
  #main {
    width: 100%;
    height: 80vh;
    display: grid;
    place-content: center;
    text-align: center;
  }

  form {
    height: 50px;
  }

  @media (max-width: 800px) {
    kbd {
      width: 100vw;
    }
  }
</style>

{% endblock %}

yellow/templates/base.html
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}YellWOWPages - Sex and Drugs in the metaverse{% endblock %}</title>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='colors.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='icon.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='1.svg') }}">
</head>
    <style>
        html, body{
            font-family: 'Courier New', Courier, monospace;
            overflow-x: hidden;
        }
        a{
            color: var(--yellow);
        }
        span{
            color: var(--purple);
        }
        strong{
            color: var(--yellow);
        }
        #dropdown{
            position: relative;
            display: inline-block;
        }
        #dropdowncontent{
            display: none;
            top: 0;
            position: absolute;
            background-color: var(--table-border-color);
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            padding: 30px 50px;
            color: var(--yellow);
            text-align: center;
            z-index: 1;
        }
        #dropdown:hover #dropdowncontent {
            display: block;
        }
        #dropdowncontent a {
          display: block;
        }
        #main{
            width: 100%;
            height: 80vh;
            display: grid;
            place-content: center;
        }
        main{
            font-size: bold;
            font-size: 10rem;
        }
        #root{
            display: flex;
            gap: 1rem;
            font-weight: 800;
            font-size: 2rem;
            align-items: center;
        }
        img{
            width: 500px;
            height: 500px;
            object-fit: contain;
        }
        #wow{
            width: 50px;
            height: 50px;
            object-fit: contain;
        }
        #footer{
            height: 12vh;
            width: 100%;
            text-align: center;
        }
        @media (max-width: 800px) {
            main{
                font-size: 3rem;
            }
        }
    </style>
<body>
  <div class="container-fluid">
    {% include 'includes/nav.html' %}

    {% block content %} {% endblock %}
  </div>

  <div id="footer">
    {{ year }} - ... [the future is w0w]
  </div>
</body>
</html>

yellow/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - Dashboard{% endblock %}
</div>

<div id="main">
  <article style="min-width: 620px">
    <Header>Welcome back <em>{{user.username}}</em>!</Header>
    Current <u>WOW address</u>: <label>
    {% if user.address %}
      <mark>{{user.address}}</mark>
    {% else %}
      <mark>empty</mark>
    {% endif %}
  </label>
    <footer>
      Change <u>WOW address</u>:
      <form action="{{ url_for('bp_routes.dashboard_address_post') }}" method="POST">
        <input type="text" name="address">
        <button data-tooltip="Make sure it is correct!">Submit</button>
      </form>
      <form action="{{ url_for('bp_routes.dashboard_address_delete') }}" method="POST">
        <button class="secondary" data-tooltip="Remove address from YelloWOWPages">Delete</button>
      </form>
    </footer>

  </article>
</div>
<style>

  #main {
    width: 100%;
    height: 85vh;
    display: grid;
    place-content: center;
  }

  @media (max-width: 800px) {
  }
</style>

{% endblock %}

yellow/templates/error.html
<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Such {{code}} error :(</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <link rel="stylesheet" href="../../static/colors.css">
    <link rel="stylesheet" href="../../static/icon.css">
</head>
    <style>
        html, body{
                font-family: 'Courier New', Courier, monospace;
            }
        #main{
            height: 100vh;
            display: grid;
            place-content: center;
        }
    </style>
<body>
    <div class="container-fluid">
        <div id="main">
            <p>Error {{code}}: {{msg}}</p>
        </div>
    </div>
</body>
</html>

yellow/templates/includes/nav.html
<nav>
  <ul>
    <li>
      <div id="dropdown">
        <i class="icon icon-menu"></i>

        <div id="dropdowncontent">
          <a href="{{ url_for('bp_routes.root') }}">Home</a>
          {% if not user %}
          <a href="{{ url_for('bp_routes.login') }}">Login</a>
          {% else %}
          <a href="{{ url_for('bp_routes.dashboard') }}">My Profile</a>
          {% endif %}
          <a href="{{ url_for('bp_routes.search') }}">Search</a>
          <a href="{{ url_for('bp_routes.about') }}">About</a>
          <a href="{{ url_for('bp_api.api_root') }}">Api</a>
          {% if user %}
          <a href="{{ url_for('bp_routes.logout') }}">Logout</a>
          {% endif %}
        </div>
      </div>
    </li>
  </ul>
  <ul>
    <li><a href="https://git.wownero.com/wownero/YellWOWPages"><i class="icon icon-edit"></i></a></li>
  </ul>
</nav>

yellow/templates/includes/search.html
<form action="{{ url_for('bp_routes.search') }}" method="GET">
  <input type="text" name="username" placeholder="Search for an username...">
</form>

yellow/templates/includes/user_results.html
<div id="addresses">
  {% for user in users %}
  <article>
    <header>
      <em><a href="{{ url_for('bp_routes.user_page', name=user.username) }}">{{user.username}}</a></em>
      <small style="float: right">Added: {{ user.created_dt }}</small>
    </header>
    <kbd>{{user.address}}</kbd>
  </article>
  {% endfor %}
</div>

yellow/templates/index.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - Sex and Drugs in the metaverse{% endblock %}
</div>

<div id="main">
    <div id="root">
        <img src="{{ url_for('static', filename='1-ico.svg') }}" alt="">
        <div style="flex-direction: column;">
            <div>
                The first <img src="{{ url_for('static', filename='wownero.png') }}" alt="" id="wow"> addresses library <br>
                from the community, for the community.
            </div>
            <div>
                <a style="text-decoration: none;" href="{{ url_for('bp_routes.search') }}">
                    <button style="max-width:320px;">start searching</button>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

yellow/templates/search.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - Yellwow{% endblock %}
</div>

<div id="main">
  {% include 'includes/search.html' %}

  {% include 'includes/user_results.html' %}
</div>

<style>
  #main {
    width: 100%;
    height: 80vh;
    display: grid;
    place-content: center;
  }

  form {
    height: 80px;
  }

  #addresses {
    width: 100%;
    height: 54vh;
    overflow-y: auto;
  }

  #addresses::-webkit-scrollbar {
    display: none;
  }
  
  @media (max-width: 800px) {
    kbd {
      width: 100vw;
    }
  }
</style>

{% endblock %}

yellow/templates/search_results.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - User{% endblock %}
</div>

<div id="main">
    {% include 'includes/search.html' %}

    <br>
    Result(s): {{users|length}}

    {% if not users %}
      <br>Nothing found...
    {% else %}
      {% include 'includes/user_results.html' %}
    {% endif %}
</div>

<style>
    #main{
        width: 100%;
        height: 80vh;
        display: grid;
        place-content: center;
    }
    form{
        height: 80px;
    }
    #addresses{
        width: 100%;
        height: 50vh;
        overflow-y: auto;
    }
    #addresses::-webkit-scrollbar{
        display: none;
    }
    @media (max-width: 800px) {
        kbd{
            width: 100vw;
        }
    }
</style>

{% endblock %}

yellow/templates/user.html
{% extends "base.html" %}
{% block content %}
<div style="display:none">
{% block title %}YellWOWPages - User{% endblock %}
</div>

<div id="main">
    {% include 'includes/search.html' %}

    {% if not users %}
      <br>Nothing found...
    {% else %}
    {% include 'includes/user_results.html' %}
    {% endif %}
</div>

<style>
    #main{
        width: 100%;
        height: 80vh;
        display: grid;
        place-content: center;
    }
    form{
        height: 80px;
    }
    #addresses{
        width: 100%;
        height: 50vh;
        overflow-y: auto;
    }
    #addresses::-webkit-scrollbar{
        display: none;
    }
    @media (max-width: 800px) {
        kbd{
            width: 100vw;
        }
    }
</style>

{% endblock %}